@url=http://localhost:4000
@json=Content-Type: application/json

###
 get {{url}}/axiostest/getdata

###
post {{url}}/axiostest/postdata
{{json}}

{
    "dataType": "json",
    "dataContent": "axios post success"
}

###
post {{url}}/axiostest/inserttodb
{{json}}

{
    "username": "u6",
    "password": "p6",
    "location": "长沙6"
}

###
get {{url}}/axiostest/findindb

###
get {{url}}/axiostest/addipfs

###
post {{url}}/axiostest/postaddipfs
{{json}}

{
    "path": "path1",
    "content": "666"
}

###
get {{url}}/datacotrol/findallindb

###
post {{url}}/datacotrol/allinserttodb
{{json}}

